#!/bin/bash
pacman -S gnome-tweak-tool
pacman -S transmission-gtk

# Aggiungo personalizzazioni grafiche
yaourt -S --noconfirm paper-icon-theme-git #solo per gnome
yaourt -S --noconfirm paper-gtk-theme-git #solo per gnome

# SISTEMO I DRIVER VIDEO
echo 'Section "Module"
    Load "modesetting"
EndSection

Section "Device"
    Identifier "nvidia"
    Driver "nvidia"
    BusID "1:0:0"
    Option "AllowEmptyInitialConfiguration"
EndSection' >> /etc/X11/xorg.conf

echo '[Desktop Entry]
Type=Application
Name=Optimus
Exec=sh -c "xrandr --setprovideroutputsource modesetting NVIDIA-0; xrandr --auto"
NoDisplay=true
X-GNOME-Autostart-Phase=DisplayServer' >> /usr/share/gdm/greeter/autostart/optimus.desktop

cp /usr/share/gdm/greeter/autostart/optimus.desktop /etc/xdg/autostart/optimus.desktop

sed -i 's/^#WaylandEnable=false/WaylandEnable=false/' /etc/gdm/custom.conf

#https://extensions.gnome.org/extension/690/easyscreencast/
#https://extensions.gnome.org/extension/1085/simple-net-speed/
#https://extensions.gnome.org/extension/307/dash-to-dock/
#https://extensions.gnome.org/extension/750/openweather/
#https://extensions.gnome.org/extension/7/removable-drive-menu/
#https://extensions.gnome.org/extension/55/media-player-indicator/
