#!/bin/bash
# Aggiungo repo multilib ed aggiorno
sudo sed -i 's/^#[[]multilib[]]/[multilib]\nInclude = \/etc\/pacman.d\/mirrorlist/' /etc/pacman.conf
sudo pacman --noconfirm -Syy
sudo pacman --noconfirm -Syu

# Installo i programmi
#pacman -S owncloud-client
sudo pacman --noconfirm -S wget
sudo pacman --noconfirm -S virtualbox virtualbox-host-modules-arch
sudo pacman --noconfirm -S firefox-i18n-it
wget http://download.virtualbox.org/virtualbox/5.2.0/Oracle_VM_VirtualBox_Extension_Pack-5.2.0-118431.vbox-extpack
sudo vboxmanage extpack install Oracle*


# plasma-nm (?)
sudo pacman --noconfirm -S konsole
sudo pacman --noconfirm -S dolphin
sudo pacman --noconfirm -S okular
# wicd (?!?!?)
sudo pacman --noconfirm -S vlc
sudo pacman --noconfirm -S qt4
sudo pacman --noconfirm -S ark
sudo pacman --noconfirm -S gedit
sudo pacman --noconfirm -S git
#pacman -S mesa lib32-mesa opengl-man-pages lib32-mesa-vdpau
sudo pacman --noconfirm -S transmission-qt
#pacman -S steam
sudo pacman --noconfirm -S libreoffice
sudo pacman --noconfirm -S openssh
#pacman -S exfat-utils
sudo pacman --noconfirm -S filezilla

# configuro yaourt
# L'USO DI MAKEPKG NON E' CONSENTITO DA ROOT, CAMBIA UTENTE
wget https://aur.archlinux.org/cgit/aur.git/snapshot/package-query.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/yaourt.tar.gz
tar -xvf yaourt.tar.gz 
tar -xvf package-query.tar.gz 
cd package-query
makepkg --noconfirm -s
makepkg --noconfirm -i
cd ..
cd yaourt
makepkg --noconfirm -s
makepkg --noconfirm -i
rm -R yaourt*
rm -R package-query*

# installo programmi da yaourt
yaourt --noconfirm -S winbox
yaourt --noconfirm -S nextcloud-client



# Configuro stampanti
pacman -S libcups
pacman -S cups ghostscript gsfonts avahi
systemctl enable avahi-daemon
systemctl enable org.cups.cupsd.socket
pacman -S hplip system-config-printer
